<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <Script>
        // for (let i = 1; i <= 10; i++) { 
        //     console.log(`9 x ${i} = ${9 * i}`); 

        // }

        const n =[1,2,3,4,5]
        let sum=0
        for(let i = 0 ; i< n.length ; i++){
            sum = sum+n[i]
            console.log(sum);
            
        }
    
    </Script>
</body>
</html>
